/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_practiceknowing_native_method_Caculate */

#ifndef _Included_com_desaco_practiceknowing_native_method_Caculate
#define _Included_com_desaco_practiceknowing_native_method_Caculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_practiceknowing_native_method_Caculate
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_desaco_practiceknowing_native_1method_Caculate_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_desaco_practiceknowing_native_method_Caculate
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_desaco_practiceknowing_native_1method_Caculate_subtract
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_desaco_practiceknowing_native_method_Caculate
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_desaco_practiceknowing_native_1method_Caculate_multiply
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_desaco_practiceknowing_native_method_Caculate
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_desaco_practiceknowing_native_1method_Caculate_divide
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
