/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_practiceknowing_native_method_NativeEncryptDecode */

#ifndef _Included_com_desaco_practiceknowing_native_method_NativeEncryptDecode
#define _Included_com_desaco_practiceknowing_native_method_NativeEncryptDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_practiceknowing_native_method_NativeEncryptDecode
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desaco_practiceknowing_native_1method_NativeEncryptDecode_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_desaco_practiceknowing_native_method_NativeEncryptDecode
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desaco_practiceknowing_native_1method_NativeEncryptDecode_decode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
