/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_practiceknowing_native_method_JniInvokeJava */

#ifndef _Included_com_desaco_practiceknowing_native_method_JniInvokeJava
#define _Included_com_desaco_practiceknowing_native_method_JniInvokeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_practiceknowing_native_method_JniInvokeJava
 * Method:    reflectJava
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_JniInvokeJava_reflectJava
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_desaco_practiceknowing_native_method_JniInvokeJava
 * Method:    reflect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_JniInvokeJava_reflect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
