/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_practiceknowing_native_method_CcallJava */

#ifndef _Included_com_desaco_practiceknowing_native_method_CcallJava
#define _Included_com_desaco_practiceknowing_native_method_CcallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_practiceknowing_native_method_CcallJava
 * Method:    callbackmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_CcallJava_callbackmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_desaco_practiceknowing_native_method_CcallJava
 * Method:    callbackIntmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_CcallJava_callbackIntmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_desaco_practiceknowing_native_method_CcallJava
 * Method:    callbackStringmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_CcallJava_callbackStringmethod
  (JNIEnv *, jobject);

/*
 * Class:     com_desaco_practiceknowing_native_method_CcallJava
 * Method:    callStaticmethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_CcallJava_callStaticmethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
