/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desaco_practiceknowing_native_method_JniScanSdcard */

#ifndef _Included_com_desaco_practiceknowing_native_method_JniScanSdcard
#define _Included_com_desaco_practiceknowing_native_method_JniScanSdcard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desaco_practiceknowing_native_method_JniScanSdcard
 * Method:    scanDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_desaco_practiceknowing_native_1method_JniScanSdcard_scanDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_desaco_practiceknowing_native_method_JniScanSdcard
 * Method:    getPathArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_desaco_practiceknowing_native_1method_JniScanSdcard_getPathArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_desaco_practiceknowing_native_method_JniScanSdcard
 * Method:    getTracksArray
 * Signature: (Ljava/lang/String;)[Lcom/desaco/practiceknowing/native_method/Track_Info;
 */
JNIEXPORT jobjectArray JNICALL Java_com_desaco_practiceknowing_native_1method_JniScanSdcard_getTracksArray
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
